// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

var listOfAnimals = /* :: */[
  /* record */[
    /* name */"Persian",
    /* species : Cat */0
  ],
  /* :: */[
    /* record */[
      /* name */"Siamese",
      /* species : Cat */0
    ],
    /* :: */[
      /* record */[
        /* name */"Scottish Fold",
        /* species : Cat */0
      ],
      /* :: */[
        /* record */[
          /* name */"Bombay",
          /* species : Cat */0
        ],
        /* :: */[
          /* record */[
            /* name */"Corgi",
            /* species : Dog */1
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

var animalNamesOnly = Belt_List.map(listOfAnimals, (function (animal) {
        return animal[/* name */0];
      }));

var someCat = /* record */[
  /* name */"Fooz",
  /* species : Cat */0
];

var someDog = /* record */[
  /* name */"Buzz",
  /* species : Dog */1
];

exports.someCat = someCat;
exports.someDog = someDog;
exports.listOfAnimals = listOfAnimals;
exports.animalNamesOnly = animalNamesOnly;
/* animalNamesOnly Not a pure module */
