// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function add5(n) {
  return n + 5 | 0;
}

function add5ToList(param) {
  return List.map(add5, param);
}

var list = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var listPlus5 = add5ToList(list);

exports.add5 = add5;
exports.add5ToList = add5ToList;
exports.list = list;
exports.listPlus5 = listPlus5;
/* listPlus5 Not a pure module */
