// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function add5(n) {
  return n + 5 | 0;
}

var listPlus5 = Belt_List.map(/* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* :: */[
            4,
            /* :: */[
              5,
              /* [] */0
            ]
          ]
        ]
      ]
    ], add5);

var someMappedReasonElements = $$Array.of_list(Belt_List.map(/* :: */[
          "Text1",
          /* :: */[
            "Text2",
            /* :: */[
              "Text3",
              /* [] */0
            ]
          ]
        ], (function (text) {
            return React.createElement("div", undefined, text);
          })));

var FastPipe = /* module */[
  /* add5 */add5,
  /* listPlus5 */listPlus5,
  /* someMappedReasonElements */someMappedReasonElements
];

exports.FastPipe = FastPipe;
/* listPlus5 Not a pure module */
