// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var fakeRealApi = "https://jsonplaceholder.typicode.com/posts";

function post(json) {
  return /* record */[
          /* userId */Json_decode.field("userId", Json_decode.$$int, json),
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* body */Json_decode.field("body", Json_decode.string, json)
        ];
}

function posts(param) {
  return Json_decode.array(post, param);
}

var Decode = /* module */[
  /* post */post,
  /* posts */posts
];

var component = ReasonReact.reducerComponent("FetchExample");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              return Curry._1(self[/* send */3], /* PostsFetch */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              if (typeof match === "number") {
                if (match !== 0) {
                  return React.createElement("div", undefined, "An error occurred!");
                } else {
                  return React.createElement("div", undefined, "Loading...");
                }
              } else {
                return React.createElement("ul", undefined, Belt_Array.map(match[0], (function (post) {
                                  return React.createElement("li", {
                                              key: String(post[/* id */1])
                                            }, post[/* title */2]);
                                })));
              }
            }),
          /* initialState */(function () {
              return /* Loading */0;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* Error */1]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            /* Loading */0,
                            (function (self) {
                                fetch(fakeRealApi).then((function (prim) {
                                            return prim.json();
                                          })).then((function (json) {
                                          console.log(json);
                                          var posts = Json_decode.array(post, json);
                                          return Promise.resolve(Curry._1(self[/* send */3], /* PostsFetched */[posts]));
                                        })).catch((function () {
                                        return Promise.resolve(Curry._1(self[/* send */3], /* PostsFailedToFetch */1));
                                      }));
                                return /* () */0;
                              })
                          ]);
                }
              } else {
                return /* Update */Block.__(0, [/* LoadedPosts */[action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.fakeRealApi = fakeRealApi;
exports.Decode = Decode;
exports.component = component;
exports.make = make;
/* component Not a pure module */
