// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

var listOfAnimals = /* :: */[
  /* record */[
    /* name */"Persian",
    /* species : Cat */0
  ],
  /* :: */[
    /* record */[
      /* name */"Siamese",
      /* species : Cat */0
    ],
    /* :: */[
      /* record */[
        /* name */"Scottish Fold",
        /* species : Cat */0
      ],
      /* :: */[
        /* record */[
          /* name */"Bombay",
          /* species : Cat */0
        ],
        /* :: */[
          /* record */[
            /* name */"Corgi",
            /* species : Dog */1
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

var catsOnly = List.filter((function (animal) {
          return animal[/* species */1] === /* Cat */0;
        }))(listOfAnimals);

var catNamesOnly = List.map((function (animal) {
        return animal[/* name */0];
      }), catsOnly);

var dogsOnly = List.filter((function (animal) {
          return animal[/* species */1] === /* Dog */1;
        }))(listOfAnimals);

var someCat = /* record */[
  /* name */"Fooz",
  /* species : Cat */0
];

var someDog = /* record */[
  /* name */"Buzz",
  /* species : Dog */1
];

exports.someCat = someCat;
exports.someDog = someDog;
exports.listOfAnimals = listOfAnimals;
exports.catsOnly = catsOnly;
exports.catNamesOnly = catNamesOnly;
exports.dogsOnly = dogsOnly;
/* catsOnly Not a pure module */
