// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var someCat = /* record */[
  /* name */"Fooz",
  /* species : Cat */0
];

var someDog = /* record */[
  /* name */"Buzz",
  /* species : Dog */1
];

var listOfCats = /* :: */[
  /* record */[
    /* name */"Persian",
    /* species : Cat */0
  ],
  /* :: */[
    /* record */[
      /* name */"Siamese",
      /* species : Cat */0
    ],
    /* :: */[
      /* record */[
        /* name */"Scottish Fold",
        /* species : Cat */0
      ],
      /* :: */[
        /* record */[
          /* name */"Bombay",
          /* species : Cat */0
        ],
        /* :: */[
          /* record */[
            /* name */"Corgi",
            /* species : Dog */1
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

exports.someCat = someCat;
exports.someDog = someDog;
exports.listOfCats = listOfCats;
/* No side effect */
