// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("ReasonElements");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var someListOfReactElements_000 = React.createElement("div", undefined);
              var someListOfReactElements_001 = /* :: */[
                React.createElement("div", undefined),
                /* :: */[
                  React.createElement("div", undefined),
                  /* [] */0
                ]
              ];
              var someListOfReactElements = /* :: */[
                someListOfReactElements_000,
                someListOfReactElements_001
              ];
              var someArrayOfReactElements = $$Array.of_list(someListOfReactElements);
              return React.createElement("div", undefined, React.createElement("div", undefined, "Your third ReasonReact component"), React.createElement("div", undefined, someArrayOfReactElements), React.createElement("div", undefined, null));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
