// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

((require('./index.css')));

var styles = {
  backgroundColor: "peach",
  width: "500px"
};

React.createElement("div", {
      style: styles
    });

exports.styles = styles;
/*  Not a pure module */
