// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var string10 = String(10);

var boolean10 = Pervasives.bool_of_string("true");

var float10 = 10;

var integer10 = 10;

var integer10Again = 10;

var integer5 = /* "a" */97;

exports.integer10 = integer10;
exports.string10 = string10;
exports.boolean10 = boolean10;
exports.float10 = float10;
exports.integer10Again = integer10Again;
exports.integer5 = integer5;
/* string10 Not a pure module */
