// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Pages$ReactTemplate = require("./Pages.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Pages$ReactTemplate.make(/* array */[])), "index1");

/*  Not a pure module */
